<?php

namespace Database\Seeders;

use App\Models\Review\Review;
use App\Models\Review\ReviewType;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ReviewSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $review_types = array(
            array('name' => 'Google Reviews','slug' => 'google-reviews','thumbnail' => NULL,'user_id' => '1','created_at' => '2023-12-18 09:42:13','updated_at' => '2023-12-18 09:42:13'),
            array('name' => 'Fiverr','slug' => 'fiverr','thumbnail' => NULL,'user_id' => '1','created_at' => '2023-12-18 09:42:13','updated_at' => '2023-12-18 09:42:13'),
            array('name' => 'Design','slug' => 'design','thumbnail' => NULL,'user_id' => '1','created_at' => '2023-12-18 09:42:13','updated_at' => '2023-12-18 09:42:13')
          );
          $reviews = array(
            array('id' => '1','name' => 'Gary','rating' => '5','date' => '2024-03-28 16:42:46','thumbnail' => NULL,'review' => '“The usability testing part was so cool. He went through the interactive elements and collected real-time feedback. Identifying accurate user behavior, Monodeep was fixing the pain points one after another. The final product was a distinguished piece of art.”','review_type_id' => '2','category_id' => '1','review_url' => NULL,'user_id' => '1','status' => '1','created_at' => '2023-12-21 11:06:19','updated_at' => '2024-02-12 11:49:55'),
            array('id' => '2','name' => 'Anthony_rhodes0z','rating' => '5','date' => '2024-03-28 16:42:46','thumbnail' => NULL,'review' => 'Great work on the design, quick response, my feedback for the page was all perfect. Thank you so much for the design, I appreciate the time and effort you devoted to the design along with the reworks. It was a pleasure to work with you!','review_type_id' => '3','category_id' => '2','review_url' => NULL,'user_id' => '1','status' => '1','created_at' => '2023-12-21 11:14:10','updated_at' => '2024-01-01 11:43:25'),
            array('id' => '3','name' => 'Peter Mark','rating' => '5','date' => '2024-03-28 16:42:46','thumbnail' => NULL,'review' => 'My photography portfolio was doing poor performance. The miserable visual presentation started killing my dreams. As I grew exponentially on several social platforms, this fall gave me a massive headache. So I modified the site’s color schemes, typography, layout, and visual hierarchy. An overall development became quite apparent in a few days. He created a cohesive and aesthetically pleasing design as well.','review_type_id' => '3','category_id' => '4','review_url' => NULL,'user_id' => '1','status' => '1','created_at' => '2023-12-26 11:45:05','updated_at' => '2024-01-01 11:43:31'),
            array('id' => '4','name' => 'Benjamin C','rating' => '5','date' => '2024-03-28 16:42:46','thumbnail' => NULL,'review' => 'His insightful ideas have transformed our brand’s online presence. Expertly crafted intuitive interfaces have greatly improved user engagement and conversions. As a busy professional, I value their efficient project management and ability to deliver high-quality designs within our tight deadlines. I really liked his quick responses.','review_type_id' => '2','category_id' => '2','review_url' => 'https://www.fiverr.com/monodeepsamanta/design-high-converting-landing-page-for-your-ads-campaign','user_id' => '1','status' => '1','created_at' => '2023-12-26 12:26:11','updated_at' => '2023-12-26 12:26:11'),
            array('id' => '5','name' => 'Sarah','rating' => '5','date' => '2024-03-28 16:42:46','thumbnail' => NULL,'review' => 'Working with Monodeep was a game-changer for our e-commerce platform. His inputs were visually stunning and optimized for seamless navigation for intuitive user interactions. Despite our time zone differences, they were always available for video conferences, making the collaboration smooth and hassle-free. His 24/7 availability was a stunner.','review_type_id' => '3','category_id' => '4','review_url' => NULL,'user_id' => '1','status' => '1','created_at' => '2023-12-26 12:42:11','updated_at' => '2024-01-01 11:43:39'),
            array('id' => '6','name' => 'Kevin','rating' => '5','date' => '2024-03-28 16:42:46','thumbnail' => NULL,'review' => 'An Amazing Talent! He communicated throughout the entire process and had a consultation meeting to ensure that we were aligned on expectations. His creativity and design work are top of the line. He delivered on time. It is worth the investment','review_type_id' => '2','category_id' => '2','review_url' => 'https://www.fiverr.com/monodeepsamanta/design-clean-website-user-interface-2019-trends?','user_id' => '1','status' => '1','created_at' => '2024-01-02 13:10:50','updated_at' => '2024-01-02 13:10:50'),
            array('id' => '7','name' => 'Gabby','rating' => '5','date' => '2024-03-28 16:42:46','thumbnail' => NULL,'review' => 'Not only was monodeepsamanta Fast, he was also able to take the pre-research we had done and translate it into an actionable UI design. We will absolutely continue our partnership with several more design and UX research needs for several projects in the upcoming months.','review_type_id' => '2','category_id' => '1','review_url' => 'https://www.fiverr.com/monodeepsamanta/design-clean-website-user-interface-2019-trends?','user_id' => '1','status' => '1','created_at' => '2024-01-02 13:14:21','updated_at' => '2024-01-02 13:14:21'),
            array('id' => '8','name' => 'Finch','rating' => '5','date' => '2024-03-28 16:42:46','thumbnail' => NULL,'review' => 'It was a perfect experience to work with this pro seller, amazing service, very short – time delivery in the highest quality, exactly like i wanted. I hope that every seller here on Fiverr will be exactly like Monode. keep rocking and thank you sir!','review_type_id' => '2','category_id' => '1','review_url' => 'https://www.fiverr.com/monodeepsamanta/design-clean-website-user-interface-2019-trends?','user_id' => '1','status' => '1','created_at' => '2024-01-02 13:16:48','updated_at' => '2024-01-02 13:16:48'),
            array('id' => '9','name' => 'Hubbard','rating' => '5','date' => '2024-03-28 16:42:46','thumbnail' => NULL,'review' => 'It was lovely experience working with Monodeep. He helped me to understand the concepts of user interface design and brand guidelines. Specifically, I really like his thoughts and approach to my users and customers. Thank you for your delivery and work with you again.','review_type_id' => '2','category_id' => '3','review_url' => 'https://www.fiverr.com/monodeepsamanta/design-clean-website-user-interface-2019-trends?','user_id' => '1','status' => '1','created_at' => '2024-01-02 13:18:36','updated_at' => '2024-01-02 13:18:36'),
            array('id' => '10','name' => 'Larry','rating' => '5','date' => '2024-03-28 16:42:46','thumbnail' => NULL,'review' => 'It was a great experience to have worked with Monodeep. Communication was excellent and quick, as was the service and product provided. They gave good time & consideration to my ideas & kept on modifying until I was a 100% satisfied.','review_type_id' => '2','category_id' => '3','review_url' => 'https://www.fiverr.com/monodeepsamanta/design-clean-website-user-interface-2019-trends?','user_id' => '1','status' => '1','created_at' => '2024-01-02 13:20:30','updated_at' => '2024-01-02 13:20:30'),
            array('id' => '11','name' => 'Karson','rating' => '5','date' => '2024-03-28 16:42:46','thumbnail' => NULL,'review' => 'This seller is a very talented artist. I highly recommend him.','review_type_id' => '2','category_id' => '1','review_url' => 'https://www.fiverr.com/monodeepsamanta/design-clean-website-user-interface-2019-trends','user_id' => '1','status' => '1','created_at' => '2024-01-02 13:21:55','updated_at' => '2024-01-02 13:21:55'),
            array('id' => '12','name' => 'Mackenzie','rating' => '5','date' => '2024-03-28 16:42:46','thumbnail' => NULL,'review' => 'Monodeep did a wonderful job! I am so pleased with the new website. It looks very professional. I like the color scheme he did, it’s fresh and modern. There is a nice combination of custom illustrations and photos. He worked quickly, and communication was very good for any revisions I needed. Will work with him for future projects!','review_type_id' => '2','category_id' => '1','review_url' => 'https://www.fiverr.com/monodeepsamanta/design-clean-website-user-interface-2019-trends','user_id' => '1','status' => '1','created_at' => '2024-01-02 13:24:07','updated_at' => '2024-01-02 13:24:07'),
            array('id' => '14','name' => 'Cameron Loren','rating' => '5','date' => '2024-03-28 16:42:46','thumbnail' => NULL,'review' => 'Awesome designer! They made my landing page look fantastic and easy to use. Communication was smooth, and they delivered on time. Highly recommended for any design project','review_type_id' => '2','category_id' => '3','review_url' => NULL,'user_id' => '1','status' => '1','created_at' => '2024-03-04 16:52:39','updated_at' => '2024-03-07 10:05:51'),
            array('id' => '15','name' => 'Juily Alla','rating' => '5','date' => '2024-03-28 16:42:46','thumbnail' => NULL,'review' => 'An incredible person to collaborate with! We\'re extremely pleased with the outcomes and eager to continue working together on all upcoming projects.','review_type_id' => '2','category_id' => '3','review_url' => NULL,'user_id' => '1','status' => '1','created_at' => '2024-03-04 16:56:02','updated_at' => '2024-03-07 10:05:38'),
            array('id' => '16','name' => 'Alessandra','rating' => '5','date' => '2024-03-28 16:42:46','thumbnail' => NULL,'review' => 'Once again, it\'s been an amazing experience collaborating with you on this project. Your consistent delivery of top-notch work always earns you a five-star rating. Without hesitation, I highly recommend you as a designer to anyone seeking exceptional quality. Looking forward to future projects with you.','review_type_id' => '2','category_id' => '3','review_url' => NULL,'user_id' => '1','status' => '1','created_at' => '2024-03-04 16:59:02','updated_at' => '2024-03-07 10:05:23'),
            array('id' => '17','name' => 'kenneth','rating' => '5','date' => '2024-03-28 16:42:46','thumbnail' => NULL,'review' => 'Monodeep\'s work quality was exceptional, and communication was smooth. Working with him was a breeze, and he even finished the task ahead of schedule. I\'m impressed and definitely plan to hire him again. Choosing him was a decision I\'m truly pleased with.','review_type_id' => '2','category_id' => '3','review_url' => NULL,'user_id' => '1','status' => '1','created_at' => '2024-03-04 17:02:18','updated_at' => '2024-03-07 10:05:09'),
            array('id' => '18','name' => 'Mackenzie Juliet','rating' => '5','date' => '2024-03-28 16:42:46','thumbnail' => NULL,'review' => 'Monodeep Samanta was highly responsive and professional, excelling in UI and UX design with a keen eye for detail. Working with him was seamless, making the entire process effortless. I strongly recommend utilizing his services; the results were truly outstanding.','review_type_id' => '2','category_id' => '3','review_url' => NULL,'user_id' => '1','status' => '1','created_at' => '2024-03-04 17:04:55','updated_at' => '2024-03-07 10:07:05'),
            array('id' => '19','name' => 'kennethjenni','rating' => '5','date' => '2024-03-28 16:42:46','thumbnail' => NULL,'review' => 'The quality of work Monodeep provided is great and the communication was well and was extremely easy to work with and also completed the work quicker than I expected. I will surely use him again and I am really pleased to pick him.','review_type_id' => '2','category_id' => '3','review_url' => NULL,'user_id' => '1','status' => '1','created_at' => '2024-03-15 12:27:51','updated_at' => '2024-03-15 12:31:18'),
            array('id' => '20','name' => 'Hearn','rating' => '5','date' => '2024-03-28 16:42:46','thumbnail' => NULL,'review' => 'An Amazing Talent! He communicated throughout the entire process and had a consultation meeting to ensure that we were aligned on expectations. His creativity and design work are top of the line. He delivered on time. It is worth the investment.','review_type_id' => '2','category_id' => '3','review_url' => NULL,'user_id' => '1','status' => '1','created_at' => '2024-03-15 12:34:34','updated_at' => '2024-03-15 12:36:23'),
            array('id' => '21','name' => 'Marks','rating' => '5','date' => '2024-03-28 16:42:46','thumbnail' => NULL,'review' => 'Not only was monodeepsamanta Fast, he was also able to take the pre research we had done and translate it into an actionable UI design. We will absolutely continue our partnership with several more design and UX research needs for several projects in the upcoming months. This is only the beginning of a long partnernship. Thank you for the help and all the time you saved us','review_type_id' => '2','category_id' => '4','review_url' => 'https://www.fiverr.com/monodeepsamanta','user_id' => '1','status' => '1','created_at' => '2024-03-15 12:49:41','updated_at' => '2024-03-15 12:49:41')
          );

          Review::insert($reviews);
          ReviewType::insert($review_types);
    }
}
